[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.17"
  HUGO_VERSION = "0.98.0"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"

[dev]
  framework = "hugo"
  targetPort = 3000

[[plugins]]
  package = "@netlify/plugin-emails"

# Schedule for deploy.js
[functions."deploy"]
  schedule = "14 * * * *"

# Schedule for disableAutoBuild.js
[functions."disableAutoBuild"]
  schedule = "18 * * * *"
