
backend:
  name: github
  repo: saragebran/oikos-archive # Path to your GitHub repository
  open_authoring: true

publish_mode: editorial_workflow

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "/img"

local_backend: true

collections: # A list of collections the CMS should be able to edit
  - name: "species" # Used in routes, i.e.: /admin/collections/:slug/edit
    label: "Species" # Used in the UI, i.e.: "New Post"
    folder: "site/content/species" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection will have
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Scientific Name", name: "category", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - label: "Common Names"
        name: "languages"
        widget: "list"
        fields:
          - {label: "Language", name: "language", widget: "string"}
          - label: "Names"
            name: "names"
            widget: "list"
            field: {label: "Name", name: "name", widget: "string"}
      - {label: "What is known about this species and the threat of its extinction?", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    create: true # Switch to false in order to not allow users to edit the pages.
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text