
backend:
  name: github
  repo: saragebran/oikos-archive # Path to your GitHub repository
  open_authoring: true

publish_mode: editorial_workflow

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "/img"

local_backend: true

collections: # A list of collections the CMS should be able to edit
  - name: "species" # Used in routes, i.e.: /admin/collections/:slug/edit
    label: "Species" # Used in the UI, i.e.: "New Post"
    folder: "site/content/species"
    path: '{{slug}}/_index'
    media_folder: ''
    public_folder: ''
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection will have
      - {label: "Draft", name: "draft", widget: "boolean", default: false, hidden: true}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", hidden: true}
      - {label: "Last Modified", name: "lastmod", widget: "datetime", hidden: true}
      - {label: "Scientific Name", name: "scientificName", widget: "string"}
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Animal", "Plant", "Fungus"]
      - label: "Common Names"
        name: "languages"
        widget: "list"
        fields:
          - {label: "Language", name: "language", widget: "string"}
          - label: "Names"
            name: "names"
            widget: "list"
            field: {label: "Name", name: "name", widget: "string"}
      - {label: "What is known about this species and the threat of its extinction?", name: "body", widget: "markdown"}
      - label: "Representation"
        name: "representations"
        create: true
        delete: false
        widget: "list"
        fields:
          - {label: "Describe your representation", name: "description", widget: "markdown", hint: "This could be a title for your representation or a longer story of how you came to know of this species or describing why you created this image. Remember you are responsible for uploading an image that you have the right to distribute. We hold no rights to the image."}
          - {label: "Image", name: "image", widget: "image" }
  - name: "pages"
    label: "Pages"
    create: true # Switch to false in order to not allow users to edit the pages.
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text