
backend:
  name: github
  repo: saragebran/oikos-archive # Path to your GitHub repository
  open_authoring: true

publish_mode: editorial_workflow

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "/img"

local_backend: true

collections:
  - name: "species"
    label: "Species"
    folder: "site/content/species"
    path: '{{slug}}/_index'
    media_folder: ''
    public_folder: ''
    create: true
    fields:
      - {label: "Draft", name: "draft", widget: "boolean", default: false, hidden: true}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", hidden: true}
      - {label: "Last Modified", name: "lastmod", widget: "datetime", hidden: true}
      - {label: "Scientific Name", name: "scientificName", widget: "string"}
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Animal", "Plant", "Fungus"]
      - label: "Common Names"
        name: "languages"
        widget: "list"
        fields:
          - {label: "Language", name: "language", widget: "string"}
          - label: "Names"
            name: "names"
            widget: "list"
            field: {label: "Name", name: "name", widget: "string"}
      - {label: "What is known about this species and the threat of its extinction?", name: "body", widget: "markdown"}
  - name: "representations"
    label: "Representations"
    identifier_field: "title"  
    folder: "site/content/species"
    path: "{{fields.species}}"
    create: true
    fields:
      - label: "Title"  
        name: "title"
        widget: "string"
        hint: Write the title of your representation.
      - label: "Species"
        name: "species"
        widget: "relation"
        collection: "species"
        search_fields: ["title", "scientificName"]
        value_field: "title"
        display_fields: ["title", "scientificName"]
      - label: "Description"
        name: "description"
        widget: "markdown"
        hint: "Describe your representation or the story behind it."
      - label: "Image"
        name: "image"
        widget: "image"
        media_folder: "{{fields.species}}/images"
        public_folder: "{{fields.species}}/images"

  - name: "pages"
    label: "Pages"
    create: true # Switch to false in order to not allow users to edit the pages.
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text