
backend:
  name: github
  repo: saragebran/oikos-archive # Path to your GitHub repository
  open_authoring: true

publish_mode: editorial_workflow

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "/img"

local_backend: true

sortable_fields:
  fields: ['commit_date', 'title', 'commit_author', 'language.en']

collections:
  - name: "species"
    label: "Species"
    slug: "{{uuid}}"
    identifier_field: "uuid"
    folder: "site/content/species"
    path: '{{slug}}/_index'
    media_folder: ''
    public_folder: ''
    create: true
    fields:
      - {label: "ID", name: "uuid", widget: "uuid", allow_regenerate: false}
      - label: "Language"
        name: "languages"
        widget: "list"
        fields:
          - {label: "Language", name: "language", widget: "string"}
          - {label: "Name", name: "names", widget: "list", field: {label: "Name", name: "name", widget: "string"}}
      - {label: "Kind", name: "kind", widget: "hidden", default: "species"}
      - {label: "Publish Date", name: "date", widget: "datetime", create: false}
      - {label: "Last Modified", name: "lastmod", widget: "datetime"}
      - {label: "Scientific Name (or other unique identifier)", name: "scientificName", widget: "string"}
      - {label: "Color", name: "color", widget: "color", hint: "What color do you think of as connected to this species?", default: "#00ff00", required: false, allowInput: true, enableAlpha: false}
      - {label: "Category", name: "category", widget: "select", options: ["Animal", "Plant", "Fungus", "Other"]}
      - {label: "What do you know about this species?", name: "body", widget: "markdown"}
  - name: "representations"
    label: "Representations"
    identifier_field: "title"  
    folder: "site/content/representations"
    path: "{{speciesid}}/{{slug}}"
    create: true
    fields:
      - {label: "Kind", name: "kind", widget: "hidden", default: "representations"}
      - label: "Species"
        name: "speciesid"
        widget: "relation"
        collection: "species"
        search_fields: ["scientificName"]
        value_field: "uuid"
        display_fields: ["scientificName"]
      - label: "Upload an image from your computer"
        name: "image"
        widget: "image"
        hint: "Max file size: 512kb"
        media_folder: "{{fields.species}}"
        public_folder: "{{fields.species}}"
      - label: "Title"  
        name: "title"
        widget: "string"
        hint: Title your artwork.
      - label: "Description"
        name: "description"
        widget: "text"
        hint: "Describe your picture or the story behind it."
  - name: "pages"
    label: "Pages"
    create: true # Switch to false in order to not allow users to edit the pages.
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text